/*
UNA VEZ CREADO EL CONTENEDOR Y QUE ESTE ESTE ACTIVO SE CONECTAMOS
DESDE DBEAVER Y CREAMOS LA BASE DE DATOS "GXCONTABLE" Y LE DAMOS LOS
PERMISOS NECESARIOS PARA EVITAR FUTUROS PROBLEMAS CON EL BUILD.
*/

-- CREAMOS LA BASE DE DATOS:
DROP USER GXCONTABLE CASCADE; 

CREATE USER GXCONTABLE
IDENTIFIED BY "TU_PASSWORD_LOCAL"  -- seria la contraseña que le quiero poner al esquema que voy a crear
DEFAULT TABLESPACE USERS
TEMPORARY TABLESPACE TEMP;

ALTER USER GXCONTABLE
QUOTA UNLIMITED ON USERS;

GRANT CREATE SESSION TO GXCONTABLE;
GRANT ALTER SESSION TO GXCONTABLE;

-- PERMISOS 
GRANT CREATE TABLE TO GXCONTABLE;
GRANT CREATE VIEW TO GXCONTABLE;
GRANT CREATE SEQUENCE TO GXCONTABLE;
GRANT CREATE PROCEDURE TO GXCONTABLE;
GRANT CREATE TRIGGER TO GXCONTABLE;
GRANT CREATE TYPE TO GXCONTABLE;
GRANT CREATE SYNONYM TO GXCONTABLE;
GRANT CREATE DATABASE LINK TO GXCONTABLE;

/*
CON RESPECTO AL RESTORE DE NUESTRA BASE DE DATOS TENEMOS QUE
EJECUTAR:
*/
CREATE OR REPLACE DIRECTORY BACKUP_DIR AS '/backup';

-- PARA COMPROBAR EJECUTAMOS:
SELECT DIRECTORY_NAME, DIRECTORY_PATH
FROM DBA_DIRECTORIES
WHERE DIRECTORY_NAME = 'BACKUP_DIR';

